name: 'TESPKG deploy to dev'
description: 'deploy to dev'
inputs:
  APP_PROJECT_NAME2:
    description: 'Who to greet'
    required: true
    default: 'APP_PROJECT_NAME2'
  APP_PROJECT_NAME3:
    description: 'Who to greet'
    required: true
    default: 'APP_PROJECT_NAME3'
  APP_PROJECT_NAME4:
    description: 'Who to greet'
    required: true
    default: 'APP_PROJECT_NAME4'
  APP_PROJECT_NAME5:
    description: 'Who to greet'
    required: true
    default: 'APP_PROJECT_NAME5'
  GITLAB_REGISTRY:
    description: 'GITLAB_REGISTRY'
    required: false
  GITHUB_REPOSITORY:
    description: 'GITHUB_REPOSITORY'
    required: false
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/deploy_to_dev.sh
      shell: bash
      env:
        APP_PROJECT_NAME3: ${{ inputs.APP_PROJECT_NAME3 }}    
        APP_PROJECT_NAME4: ${{ inputs.APP_PROJECT_NAME4 }}    
        GITLAB_REGISTRY: ${{ inputs.GITLAB_REGISTRY }}
        GITHUB_REPOSITORY: ${{ inputs.GITHUB_REPOSITORY }}
