name: 'TESPKG deploy to dev'
description: 'deploy to dev'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  inputENV:  # id of input
    description: 'Who to greet'
    required: true
    default: 'along'
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/deploy_to_dev.sh
      shell: bash