name: 'TESPKG deploy to dev'
description: 'deploy to dev'
inputs:
  APP_CHART_NAME:
    description: 'APP_CHART_NAME'
    required: true
    default: ${{ github.repository }}
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/deploy_to_dev.sh
      shell: bash
      env:
        APP_CHART_NAME: ${{ inputs.APP_CHART_NAME }}