name: 'TESPKG Kubernetes toolbox '
description: 'Github Action with Kubernetes tools: helm yq'
branding:
  icon: 'command'
  color: 'blue'
# inputs:
#   who-to-greet:  # id of input
#     description: 'Who to greet'
#     required: true
#     default: 'World'
# outputs:
#   random-number:
#     description: "Random number"
#     value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/install_tools.sh
      shell: bash