name: 'TESPKG deploy to dev'
description: 'deploy to dev'
inputs:
  APP_PROJECT_NAME3:  # id of input
    description: 'Who to greet'
    required: true
    default: 'along'
  APP_PROJECT_NAME4:  # id of input
    description: 'Who to greet'
    required: true
    default: 'along'
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/deploy_to_dev.sh
      shell: bash