name: 'TESPKG deploy to dev'
description: 'deploy to dev'
inputs:
  APP_PROJECT_NAME2:
    description: 'Who to greet'
    required: true
    default: 'APP_PROJECT_NAME2'
  APP_PROJECT_NAME3:
    description: 'Who to greet'
    required: true
    default: 'APP_PROJECT_NAME3'
  APP_PROJECT_NAME4:
    description: 'Who to greet'
    required: true
    default: 'APP_PROJECT_NAME4'
  APP_PROJECT_NAME5:
    description: 'Who to greet'
    required: true
    default: 'APP_PROJECT_NAME5'
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/deploy_to_dev.sh
      shell: bash
      env:
        APP_PROJECT_NAME5: ${{ inputs.APP_PROJECT_NAME5 }}      