name: 'TESPKG deploy to dev'
description: 'deploy to dev'
inputs:
  APP_SOURCE_REPO:
    description: 'APP_SOURCE_REPO'
    required: true
    default: ${{ github.repository }}
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/deploy_to_dev.sh
      shell: bash
      env:
        APP_SOURCE_REPO: ${{ inputs.APP_SOURCE_REPO }}